name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Set up JDK 11
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Docker
        run: docker-compose up -d
      - name: Check Docker
        run: docker-compose ps
      - name: Build with Gradle
        run: ./gradlew test